steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ontario-eco-translator-repo/app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/ontario-eco-translator-repo/app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ontario-eco-translator-api
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/ontario-eco-translator-repo/app
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --add-cloudsql-instances=ontario-eco-translator-492405:us-central1:ontario-eco-sql
      - --set-secrets=DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_NAME=DB_NAME:latest,CLOUD_SQL_CONNECTION_NAME=CLOUD_SQL_CONNECTION_NAME:latest

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ontario-eco-translator-repo/app'